### ISSUE TITLE
Add global step templates

### ISSUE THREAD

**Issue by JeanMertz** [blendle/automaat#46]
Once the list of tasks grows, you get a lot of copy/pasting of commonly-used steps, such as this one:

```yaml
steps:
  - name: Validate Customer UUID
    description: |-
      Validate the customer UUID format as UUIDv4.
    processor:
      stringRegex:
        input: '{{ var["Customer UUID"] }}'
        regex: >-
          \A[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}\z
        mismatchError: The provided customer UUID has an invalid format.

  - name: Other Step
    ...
```

It would be nice if there was some kind of (optional) feature that allows you to define global steps (somewhat similar to global variables #24) that can be shared across tasks.

For starters, such a step could be used as:

```yaml
steps:
  - template: Validate Customer UUID
  - name: Other Step
    ...
```

The concept would probably be based on inheritance. You can define a `template` key to inherit any properties set in that template, and then override what you need changed in your own task.

There are still plenty of design decisions to make, and gotchas to consider, but the general concept of this is very useful for larger Automaat instances.

**Comment by JeanMertz** [comment]
Another approach to inheritance would be to allow step templates to define their _own_ required arguments, so that a template can be configured on a per-need basis, for example:

```yaml
steps:
  - template:
      id: Regex String Validation
      config:
        name: Validate Customer UUID
        regex: ... 
  - name: Other Step
    ...
```

But, this would make things way more complex, for probably too little gain. Just putting this out there as a possibility, but I'm not a big fan of this over the inheritance approach.
